import express from 'express';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI, Type, Schema } from '@google/genai';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Ensure env is loaded explicitly
dotenv.config({ override: true });

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Route for Gemini analysis
  app.post('/api/analyze', async (req, res) => {
    try {
      const { comment } = req.body;
      
      if (!comment) {
        return res.status(400).json({ error: 'Comment is required' });
      }

      const apiKey = process.env.GEMINI_API_KEY;
      console.log('DEBUG API KEY IN ENDPOINT:', apiKey);
      
      if (!apiKey || apiKey === 'MY_GEMINI_API_KEY') {
        return res.status(500).json({ error: 'Gemini API Key is missing or using placeholder value. Please configure it in your Secrets panel or in the .env file.' });
      }

      const ai = new GoogleGenAI({ apiKey });

      const systemInstruction = `
You are Aegis AI, a highly robust content moderation system. Your primary function is to scan comments and accurately differentiate between harmless situational sarcasm and actual toxic behavior.

Your strict boundaries and rules are:
1. **Harmless Sarcasm is SAFE:** Sarcasm regarding personal situations, inanimate objects, or minor inconveniences (e.g., "Oh brilliant, I spilled coffee on my shirt", "Great, another Monday") MUST be marked as 'Safe'.
2. **Targeted Toxicity is NOT SAFE:** You must ONLY flag a comment as harmful if it falls into one of these two categories:
   - 'Targeted Hate': Slurs, discrimination, or aggressive sarcasm specifically targeting a community, marginalized group, or an individual person.
   - 'Sexual/Vulgar': Explicit sexual content or aggressive, extreme profanity.
3. **The Final Verdicts:** Every comment parameter MUST be classified as ONLY ONE of the following exactly: 'Safe', 'Targeted Hate', or 'Sexual/Vulgar'.

You must return a JSON response matching the specified schema.
`;

      const responseSchema: Schema = {
        type: Type.OBJECT,
        properties: {
          verdict: {
            type: Type.STRING,
            enum: ['Safe', 'Targeted Hate', 'Sexual/Vulgar'],
            description: "The final verdict categorization."
          },
          isSarcastic: {
            type: Type.BOOLEAN,
            description: "Whether the comment utilizes sarcasm."
          },
          confidenceScore: {
            type: Type.INTEGER,
            description: "Confidence score from 0 to 100."
          },
          reasoning: {
            type: Type.STRING,
            description: "A 1-2 sentence explanation. If safe sarcasm, explain it doesn't target a person/community. If hate, explain who is targeted."
          }
        },
        required: ["verdict", "isSarcastic", "confidenceScore", "reasoning"],
      };

      const response = await ai.models.generateContent({
        model: 'gemini-3.1-pro-preview',
        contents: comment,
        config: {
          systemInstruction,
          responseMimeType: 'application/json',
          responseSchema,
        }
      });

      const text = response.text;
      if (!text) {
        throw new Error('No response generated by Gemini');
      }

      // Parse and send the result
      const result = JSON.parse(text);
      res.json(result);
      
    } catch (error: any) {
      console.error('Error analyzing comment:', error);

      const errorMessage = error?.message || String(error);
      if (errorMessage.includes('API key not valid') || errorMessage.includes('API_KEY_INVALID')) {
        return res.status(500).json({ error: 'The provided Gemini API Key is invalid. Please verify the key in your Secrets panel.' });
      } else if (errorMessage.includes('quota') || errorMessage.includes('429')) {
        return res.status(429).json({ error: 'Gemini API Quota Exceeded. Please check your billing details or retry later.' });
      }

      // Fallback to sending the raw parsed error message from Google Cloud
      try {
        const parsed = JSON.parse(errorMessage.replace('Error: ', ''));
        if (parsed?.error?.message) {
          return res.status(500).json({ error: `Gemini Error: ${parsed.error.message}` });
        }
      } catch (e) {
        // Not a JSON error string
      }

      res.status(500).json({ error: errorMessage });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    // Support wildcard routing for React Router if needed
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer().catch(console.error);
